'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq

Partial Public Class vscyrmEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=vscyrmEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property cargos() As DbSet(Of cargo)
    Public Property empleadoes() As DbSet(Of empleado)
    Public Property marcajes() As DbSet(Of marcaje)
    Public Property reglas() As DbSet(Of regla)
    Public Property turno_complejo() As DbSet(Of turno_complejo)
    Public Property turno_sencillo() As DbSet(Of turno_sencillo)

    Public Overridable Function Buscar_Horario(codigo As String) As ObjectResult(Of Buscar_Horario_Result)
        Dim codigoParameter As ObjectParameter = If(codigo IsNot Nothing, New ObjectParameter("Codigo", codigo), New ObjectParameter("Codigo", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Buscar_Horario_Result)("Buscar_Horario", codigoParameter)
    End Function

End Class
